Repository owncloud/files_texteditor, pull requests merged in 2020-12, with the labels that each got.

#328 [Tests-Only][CI] fix the starlark code for reduced ci after merge and sonarcloud
  .drone.star
  .gitignore
  sonar-project.properties
Labels: QA-team

#329 [Tests-Only][CI] fix sonarcloud reporting in CI
  .drone.star
  sonar-project.properties
Labels: QA-team

#331 Enhance context menu
  js/editor.js
Labels: 4 - To release

#333 Adding encodings (GB2312, GBK ,BIG5, SJIS-win and EUC-JP)
  controller/filehandlingcontroller.php
Labels: 3 - To review

#334 [tests-only] Implement latest .drone.star as at 2020-12-22
  .drone.star
  phpstan.neon
  vendor-bin/behat/composer.json
  vendor-bin/php_codesniffer/composer.json
Labels: 3 - To review, QA-team
